### ISSUE TITLE
TypeError: Request path contains unescaped characters

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#109]
`getTokensForEditor` fails on any file with a space (and probably other possibilities) in its path.

```
_http_client.js:53 Uncaught (in promise) TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:53:11)
    at Object.exports.request (http.js:31:10)
    at Promise (/Users/adam/.atom/packages/kite/node_modules/kite-installer/lib/client.js:57:33)
    at Client.request (/Users/adam/.atom/packages/kite/node_modules/kite-installer/lib/client.js:49:12)
    at Object.getTokensForEditor (/Users/adam/.atom/packages/kite/lib/data-loader.js:120:52)
    at KiteEditor.updateTokens (/Users/adam/.atom/packages/kite/lib/kite-editor.js:130:16)
    at subs.add.editor.onDidStopChanging (/Users/adam/.atom/packages/kite/lib/kite-editor.js:48:50)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1371:25
```

my filepath here is `/Users/adam/Dropbox (Kite)/quick_demo.py`.

**Comment by abe33** [comment]
That's fixed on master, it's waiting for publication.
