### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by ckydodo** [kiteco/atom-plugin#123]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.16.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At C:\Users\cky\.atom\packages\kite\lib\urls.js:9

TypeError: Cannot read property 'getText' of undefined
    at tokensPath (/packages/kite/lib/urls.js:9:27)
    at Object.getTokensForEditor (/packages/kite/lib/data-loader.js:171:18)
    at KiteEditor.updateTokens (/packages/kite/lib/kite-editor.js:94:23)
    at setTimeout (/packages/kite/lib/kite-editor.js:85:24)
```

### Commands

```
     -9:09.0 core:backspace (input.hidden-input)
     -9:05.8.0 core:copy (input.hidden-input)
  3x -9:04.7.0 core:backspace (input.hidden-input)
  2x -6:04.6.0 core:confirm (input.hidden-input)
     -5:06.6.0 core:move-right (atom-pane.pane.active)
  2x -4:59.2.0 core:backspace (atom-pane.pane.active)
     -4:13.6.0 core:confirm (input.hidden-input)
     -3:47.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-python 1.8.60 
file-icons 2.0.17 
kite 0.16.2 
predawn-syntax 1.0.4 
script 3.14.1 
```

**Comment by abe33** [comment]
Hi @ckydodo, I just published a patch for that issue in v0.16.3, let me know if you still get that error.
