### ISSUE TITLE
Uncaught Error: Command failed: "$ATOM_HOME/packages\kite\node_modules\kite-installer\lib\support...

### ISSUE THREAD

**Issue by wegfawefgawefg** [kiteco/atom-plugin#155]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.20.2

### Stack Trace

Uncaught Error: Command failed: "C:\Users\time\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat"
'"C:\Users\time\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat"' is not recognized as an internal or external command,
operable program or batch file.

```
At child_process.js:538

Error: Command failed: "C:\Users\time\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat"
'"C:\Users\time\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat"' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:495:13)
    at Object.execSync (child_process.js:535:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at Object.arch (/packages/kite/node_modules/kite-installer/lib/support/windows.js:63:33)
    at Object.isOSVersionSupported (/packages/kite/node_modules/kite-installer/lib/support/windows.js:72:17)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/support/windows.js:76:17)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/state-controller.js:62:25)
    at Object.isKiteInstalled (/packages/kite/node_modules/kite-installer/lib/state-controller.js:72:17)
    at Object.isKiteRunning (/packages/kite/node_modules/kite-installer/lib/state-controller.js:132:17)
    at Object.isKiteReachable (/packages/kite/node_modules/kite-installer/lib/state-controller.js:157:17)
    at Object.isUserAuthenticated (/packages/kite/node_modules/kite-installer/lib/state-controller.js:179:17)
    at Object.handleState (/packages/kite/node_modules/kite-installer/lib/state-controller.js:36:17)
    at KiteApp.connect (/packages/kite/lib/kite-app.js:150:28)
    at Object.connect (/packages/kite/lib/kite.js:288:21)
    at subscriptions.add.getStatusItem.onDidClick.status (/packages/kite/lib/kite.js:74:14)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /packages/kite/lib/elements/kite-status.js:48:20)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
kite 0.20.2 
language-lua 0.9.11 
love-atom 2.5.1 
```

**Comment by abe33** [comment]
I'm not sure of what is going wrong here, as this error message seems to have a wide range of possible origins. Is the corresponding `bat` file exists at the given path?

**Comment by wolfhawke** [comment]
Note that there is a slash missing between the C:\Users\time and the .atom subfolder. The path should be: "C:\Users\time\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat"

**Comment by abe33** [comment]
Hmm, but that might just be some markdown formatting occuring on github, because the backslash is present in the stack trace below.
