### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by goldpc2008** [kiteco/atom-plugin#173]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.21.2

### Stack Trace

Uncaught Error: Cannot find module './kite'

```
At module.js:457

Error: Cannot find module './kite'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at ensureKite (/packages/kite/lib/data-loader.js:28:48)
    at Object.projectDirForEditor (/packages/kite/lib/data-loader.js:42:5)
    at /packages/kite/lib/elements/kite-status-panel.js:154:32)
    at /packages/kite/lib/elements/kite-status-panel.js:50:17)
    at subscriptions.add.getStatusItem.onDidClick.status (/packages/kite/lib/kite.js:69:29)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at /packages/kite/lib/elements/kite-status.js:48:20)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
kite 0.21.2 
```

**Comment by jlozano** [comment]
@abe33 I see this occasionally as well, any idea what might be causing it?

**Comment by abe33** [comment]
@jlozano Are you also seeing that error on a click on the status icon? That's what the stack trace seems to suggest. 
But the weird thing is that if we can see the status icon, then that means that Atom has loaded the `kite.js` file (the one that it cannot find later) to consume the status bar api provider we've defined in `package.json`. 
My guess is that when kited updates the plugin there's a window during the time `apm` takes to rebuid the module cache, and if we need to require that file in that window then the request might fail because the module cache is in a partial state.

**Comment by jansorg** [comment]
Closing, as this is an old issue. If this still happens for you, then please reopen it.
