### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol' of undefined

### ISSUE THREAD

**Issue by ikiru** [kiteco/atom-plugin#202]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.26.0

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol' of undefined

```
At /Users/jeffwinkler/.atom/packages/kite/lib/kite-editor.js:123

TypeError: Cannot read property 'Symbol' of undefined
    at KiteEditor.openTokenDefinition (/packages/kite/lib/kite-editor.js:123:61)
    at KiteEditor.openDefinitionAtRange (/packages/kite/lib/kite-editor.js:139:17)
    at subscriptions.add.scheme.onDidClickLink (/packages/kite/lib/elements/kite-links.js:72:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at LinkScheme.subscription.addDelegatedEventListener (/packages/kite/lib/link-scheme.js:16:22)
    at nodeAndParents.forEach (/packages/kite/lib/utils.js:65:7)
    at Array.forEach (native)
    at /packages/kite/lib/utils.js:60:28)
```

### Commands

```
     -4:46.1.0 application:add-project-folder (input.hidden-input)
     -4:43.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
 54x -3:08.7.0 core:backspace (input.hidden-input)
     -2:34.8.0 core:save (input.hidden-input)
     -2:34.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
     -2:29.6.0 atom-beautify:beautify-editor (input.hidden-input)
     -2:12.6.0 emmet:toggle-comment (input.hidden-input)
     -2:12.6.0 editor:toggle-line-comments (input.hidden-input)
     -2:11.2.0 emmet:toggle-comment (input.hidden-input)
     -2:11.2.0 editor:toggle-line-comments (input.hidden-input)
     -2:06.2.0 core:save (input.hidden-input)
     -0:51.5.0 editor:newline (input.hidden-input)
     -0:37.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-bootstrap3 1.2.12 
atom-copy-on-select 1.4.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-python 1.8.64 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.7 
flask-snippets 0.3.3 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
kite 0.26.0 
language-mongodb 0.3.1 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-python-pep8 0.2.0 
linter-spell 0.13.2 
linter-spell-html 0.6.2 
linter-spell-javascript 0.7.2 
linter-tidy 2.3.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
multi-cursor 2.1.5 
open-recent 5.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
python-autopep8 0.1.3 
python-indent 1.0.3 
simple-drag-drop-text 0.3.4 
```

**Comment by abe33** [comment]
Hi @ikiru, thanks for the report, the patch for this issue should be available soon.
