### ISSUE TITLE
Uncaught Error: spawnSync C:/WINDOWS\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by CheshireCat12** [kiteco/atom-plugin#208]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.26.0

### Stack Trace

Uncaught Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOENT

```
At child_process.js:538

Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at Object.execSync (child_process.js:529:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at Object.arch (/packages/kite/node_modules/kite-installer/lib/support/windows.js:58:33)
    at Object.isOSVersionSupported (/packages/kite/node_modules/kite-installer/lib/support/windows.js:67:17)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/support/windows.js:71:17)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/state-controller.js:62:25)
    at Object.isKiteInstalled (/packages/kite/node_modules/kite-installer/lib/state-controller.js:72:17)
    at Object.isKiteRunning (/packages/kite/node_modules/kite-installer/lib/state-controller.js:132:17)
    at Object.isKiteReachable (/packages/kite/node_modules/kite-installer/lib/state-controller.js:157:17)
    at Object.isUserAuthenticated (/packages/kite/node_modules/kite-installer/lib/state-controller.js:179:17)
    at Object.handleState (/packages/kite/node_modules/kite-installer/lib/state-controller.js:36:17)
    at KiteApp.connect (/packages/kite/lib/kite-app.js:164:28)
    at check (/packages/kite/lib/kite.js:322:40)
    at Object.checkTextEditor (/packages/kite/lib/kite.js:368:9)
    at subscriptions.add.atom.workspace.onDidChangeActivePaneItem.item (/packages/kite/lib/kite.js:77:14)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.17.2/resources/app/src/workspace.js:489:1)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/workspace-center.js:16:1)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane-container.js:280:1)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:318:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:471:1)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-2048 3.1.0 
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-python 1.8.64 
busy-signal 1.4.3 
chester-atom-syntax 0.2.0 
emmet 2.4.3 
intentions 1.1.2 
kite 0.26.0 
language-latex 1.0.0 
language-restructuredtext 1.1.0 
latex 0.43.0 
latexer 0.3.0 
linter 2.1.4 
linter-flake8 2.2.1 
linter-php 1.3.2 
linter-python-pep8 0.2.0 
linter-ui-default 1.6.1 
python-indent 1.0.3 
python-tools 0.6.9 
rst-preview-pandoc 0.1.12 
```

**Comment by jansorg** [comment]
@CheshireCat12 Do you still experience this?
Please reopen if it's still a valid issue.
