### ISSUE TITLE
Uncaught Error: Cannot find module './support/windows'

### ISSUE THREAD

**Issue by DonPhysii** [kiteco/atom-plugin#234]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.38.0

### Stack Trace

Uncaught Error: Cannot find module './support/windows'

```
At C:\ProgramData\Physii Daraxerxes\atom\app-1.19.4\resources\app\static\<embedded>:1

Error: Cannot find module './support/windows'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:/ProgramData/Physii Daraxerxes/atom/app-1.19.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:/ProgramData/Physii Daraxerxes/atom/app-1.19.4/resources/app/src/module-cache.js:354:58)
    at Module.require (C:/ProgramData/Physii%20Daraxerxes/atom/app-1.19.4/resources/app/static/index.js:40:43)
    at require (C:/ProgramData/Physii Daraxerxes/atom/app-1.19.4/resources/app/src/native-compile-cache.js:66:33)
    at Object.getSupport (/packages/kite/node_modules/kite-installer/lib/constants.js:20:30)
    at /packages/kite/node_modules/kite-installer/lib/state-controller.js:20:21)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/state-controller.js:62:16)
    at Object.isKiteInstalled (/packages/kite/node_modules/kite-installer/lib/state-controller.js:80:17)
    at Object.isKiteRunning (/packages/kite/node_modules/kite-installer/lib/state-controller.js:152:17)
    at Object.isKiteReachable (/packages/kite/node_modules/kite-installer/lib/state-controller.js:213:12)
    at Object.isUserAuthenticated (/packages/kite/node_modules/kite-installer/lib/state-controller.js:239:17)
    at Object.handleState (/packages/kite/node_modules/kite-installer/lib/state-controller.js:36:17)
    at KiteApp.connect (/packages/kite/lib/kite-app.js:164:28)
    at Object.connect (/packages/kite/lib/kite.js:330:21)
    at pollingInterval.setInterval (/packages/kite/lib/kite.js:303:14)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.10.2 
Hydrogen 1.20.0 
kite 0.38.0 
script 3.15.0 
spacegray-atom-dark-syntax 1.3.2 
```

**Comment by abe33** [comment]
Hi @DonPhysii, it looks like there was some issue during the dependencies install, did you still see that error after a restart? If not, it might just have been a race condition, otherwise can you try to run run `apm install` in the plugin directory (it shiould be in your home, in a `.atom/packages/kite` directory) to see if it helps?

**Comment by jansorg** [comment]
@DonPhysii Closing the very old issue. Please reopen if you're still experiencing this.
