### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by kantamei** [kiteco/atom-plugin#250]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.43.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at /packages/kite/node_modules/kite-installer/lib/support/windows.js:12:36)
    at /packages/kite/node_modules/kite-installer/lib/support/windows.js:158:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at Object.getSupport (/packages/kite/node_modules/kite-installer/lib/constants.js:20:30)
    at /packages/kite/node_modules/kite-installer/lib/state-controller.js:20:21)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/state-controller.js:62:16)
    at Object.isKiteInstalled (/packages/kite/node_modules/kite-installer/lib/state-controller.js:80:17)
    at Object.isKiteRunning (/packages/kite/node_modules/kite-installer/lib/state-controller.js:152:17)
    at Object.isKiteReachable (/packages/kite/node_modules/kite-installer/lib/state-controller.js:213:12)
    at Object.isUserAuthenticated (/packages/kite/node_modules/kite-installer/lib/state-controller.js:239:17)
    at Object.handleState (/packages/kite/node_modules/kite-installer/lib/state-controller.js:36:17)
    at KiteApp.connect (/packages/kite/lib/kite-app.js:176:28)
    at Object.connect (/packages/kite/lib/kite.js:335:21)
    at pollingInterval.setInterval (/packages/kite/lib/kite.js:308:14)
```

### Commands

```
```

### Non-Core Packages

```
hydrogen-launcher 1.2.1 
kite 0.43.2 
linter 2.2.0 
simplified-chinese-menu 5.3.4 
```

**Comment by jansorg** [comment]
@kantamei Please reopen if this is still relevant. 
Sorry for this very late reply!
