### ISSUE TITLE
when i open the atom program (Failed to activate the kite package)

### ISSUE THREAD

**Issue by pabloemmanueldeleo** [kiteco/atom-plugin#253]
ENOENT: no such file or directory, open 'C:\Users\Emma\.atom\packages\kite\assets\kitesync.svg'
Hide Stack Trace
Error: ENOENT: no such file or directory, open 'C:\Users\Emma\.atom\packages\kite\assets\kitesync.svg'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.<anonymous> (C:\Users\Emma\.atom\packages\kite\lib\elements\kite-logo.js:5:31)
    at Object.<anonymous> (C:\Users\Emma\.atom\packages\kite\lib\elements\kite-logo.js:29:3)
    at Module.get_Module._compile (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/Emma/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (C:\Users\Emma\.atom\packages\kite\lib\elements\kite-status.js:3:1)
    at Object.<anonymous> (C:\Users\Emma\.atom\packages\kite\lib\elements\kite-status.js:150:3)
    at Module.get_Module._compile (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/Emma/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\native-compile-cache.js:66:33)
    at Object.getStatusItem (C:\Users\Emma\.atom\packages\kite\lib\kite.js:578:37)
    at Object.activate (C:\Users\Emma\.atom\packages\kite\lib\kite.js:65:10)
    at Package.module.exports.Package.activateNow (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package.js:253:25)
    at C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package.js:99:21)
    at C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package-manager.js:645:40)
    at C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\config.js:367:24)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\package-manager.js:603:52)
    at C:\Users\Emma\AppData\Local\atom\app-1.20.1\resources\app\src\atom-environment.js:843:36

**Comment by abe33** [comment]
Hi @pabloemmanueldeleo, it looks like there was some issue when installing the plugin, could you try to remove the plugin in your `packages` directory and retry to install it using `apm install kite`? Sometime apm/npm installs can be quite unreliable.

**Comment by pabloemmanueldeleo** [comment]
Thank you, i can try that.

**Comment by Danrusu55** [comment]
I tried this and it didnt work. Still getting the issue.

**Comment by ekginn2** [comment]
Is there a fix for this error?

**Comment by jcoelho-pt** [comment]
I had the same problema and fixed it doing this:
1. Atom: Uninstall Kite package and close the app
2. Open your Kite Engine app and using it,  install Kite plugin to Atom
3. Open Atom and it must be solved

**Comment by pritam199902** [comment]
Getting this error..

Failed to install Atom at path 
C:\Users\wwwpr\AppData\Local\atom\app-1.45.0\atom.exe
error running apm "install kite": exec: "apm": executable file not found in %PATH%

What should I do??

**Comment by santiagodemierre** [comment]
/home/santiago/.atom/packages/kite/dist/main.js:6165
>>>>>>> Patch autocomplete-plus/snippets insert(...) to not insert indentation for Kite completions.
^^^
SyntaxError: Unexpected token >>>
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/usr/share/atom/resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695133)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3231254)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3219238)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3219016)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3216626)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3218876)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3218819)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382452)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382068)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:331716)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382018)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381568)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:717298)
