### ISSUE TITLE
"Go do definition" opens empty/wrong file

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#257]
Windows 10

- Hover over a token
- Click on "def"
- An empty file is opened. It seems to be named as the driver letter here.

The API returns the path as windows path:
```json
 "report": {
    "definition": {
      "filename": "c:\\users\\jansorg\\pycharmprojects\\testpython\\whitelisted\\foo.py",
      "line": 10
    },
 ...
}
```

![atom-open-definition](https://user-images.githubusercontent.com/11473063/31170588-e051afe4-a8fc-11e7-9ab9-04755c455777.png)

**Comment by jansorg** [comment]
I'm getting this after clicking on def:
```
GET http://127.0.0.1:46624/api/buffer/atom/:windows:C:Users:jansorg:PycharmProjects:TestPython:whitelisted:foo.py/93270d56bbf465186c6c7c5b67574eab/tokens 410 (Gone)
Promise @ C:\Users\jansorg\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:78
request @ C:\Users\jansorg\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:48
getTokensForEditor @ C:\Users\jansorg\.atom\packages\kite\lib\data-loader.js:244
updateTokens @ C:\Users\jansorg\.atom\packages\kite\lib\kite-editor.js:88
subscribeToEditor @ C:\Users\jansorg\.atom\packages\kite\lib\kite.js:604
app.connect.then.state @ C:\Users\jansorg\.atom\packages\kite\lib\kite.js:363
C:\Users\jansorg\.atom\packages\kite\lib\kite-editor.js:149 Uncaught (in promise) TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\point.js:63:21)
    at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1198:19)
    at MarkerLayer.module.exports.MarkerLayer.setMarkerRange (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\marker-layer.js:415:35)
    at Marker.module.exports.Marker.update (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\marker.js:341:26)
    at Marker.module.exports.Marker.setHeadPosition (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\marker.js:144:25)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\display-marker.js:146:38)
    at C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\cursor.js:75:37
    at Cursor.module.exports.Cursor.changePosition (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\cursor.js:644:13)
    at Cursor.module.exports.Cursor.setBufferPosition (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\cursor.js:73:25)
    at C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\text-editor.js:1922:29
    at C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\text-editor.js:2180:19
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:953:24)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\text-editor.js:1673:32)
    at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\text-editor.js:2174:25)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (C:\Users\jansorg\AppData\Local\atom\app-1.21.0\resources\app\src\text-editor.js:1921:25)
    at atom.workspace.open.then.editor (C:\Users\jansorg\.atom\packages\kite\lib\kite-editor.js:149:18)
module.exports.Point.assertValid @ <embedded>:73406
module.exports.TextBuffer.clipPosition @ <embedded>:32171
module.exports.MarkerLayer.setMarkerRange @ <embedded>:74851
module.exports.Marker.update @ <embedded>:130623
module.exports.Marker.setHeadPosition @ <embedded>:130426
module.exports.DisplayMarker.setHeadBufferPosition @ <embedded>:214717
(anonymous) @ <embedded>:34983
module.exports.Cursor.changePosition @ <embedded>:35552
module.exports.Cursor.setBufferPosition @ <embedded>:34981
(anonymous) @ <embedded>:4183
(anonymous) @ <embedded>:4441
module.exports.TextBuffer.transact @ <embedded>:31926
module.exports.TextEditor.transact @ <embedded>:3934
module.exports.TextEditor.moveCursors @ <embedded>:4435
module.exports.TextEditor.setCursorBufferPosition @ <embedded>:4182
atom.workspace.open.then.editor @ C:\Users\jansorg\.atom\packages\kite\lib\kite-editor.js:149
C:\Users\jansorg\.atom\packages\kite\node_modules\kite-installer\lib\browser-client.js:78 POST http://127.0.0.1:46624/clientapi/editor/event 403 (Forbidden)
```

**Comment by jansorg** [comment]
Fixed for Windows with current master
