### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Value' of undefined

### ISSUE THREAD

**Issue by michielbakker** [kiteco/atom-plugin#263]
1. Installed Atom 1.21.0 x64 for Mac 10.12
2. Installed Kite

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.47.1

### Stack Trace

Uncaught TypeError: Cannot read property 'Value' of undefined

```
At /Users/michielbakker/.atom/packages/kite/node_modules/kite-installer/lib/installer.js:224

TypeError: Cannot read property 'Value' of undefined
    at auth (/packages/kite/node_modules/kite-installer/lib/installer.js:224:55)
    at authTimerID.setTimeout (/packages/kite/node_modules/kite-installer/lib/installer.js:231:7)
```

### Commands

```
     -1:17.1.0 settings-view:open (atom-pane.pane.active)
  3x -1:07.5.0 core:backspace (input.hidden-input)
     -1:06.4.0 core:confirm (input.hidden-input)
     -0:57.2.0 core:backspace (input.hidden-input)
     -0:54.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
kite 0.47.1 
```

**Comment by jansorg** [comment]
@michielbakker A few weeks ago we've fixed a few issues around the installation. Do you still experience this?
