### ISSUE TITLE
Uncaught Error: Cannot find module './kite'

### ISSUE THREAD

**Issue by Bharry1995** [kiteco/atom-plugin#265]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.48.1

### Stack Trace

Uncaught Error: Cannot find module './kite'

```
At module.js:472

Error: Cannot find module './kite'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:66:33)
    at ensureKite (/packages/kite/lib/data-loader.js:32:48)
    at Object.getTokensForEditor (/packages/kite/lib/data-loader.js:241:5)
    at KiteEditor.updateTokens (/packages/kite/lib/kite-editor.js:88:20)
    at delayPromise (/packages/kite/lib/kite-editor.js:81:69)
    at setTimeout (/packages/kite/lib/utils.js:200:7)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
busy-signal 1.4.3 
Hydrogen 1.23.0 
intentions 1.1.5 
kite 0.48.1 
linter 2.2.0 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
```

**Comment by jansorg** [comment]
@Bharry1995 Please reopen if you're still getting this.
