### ISSUE TITLE
Uncaught Error: Couldn't convert text to a String

### ISSUE THREAD

**Issue by rahulbhat44** [kiteco/atom-plugin#277]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.52.0

### Stack Trace

Uncaught Error: Couldn't convert text to a String

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:550

Error: Couldn't convert text to a String
    at TextBuffer.module.exports.TextBuffer.getText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:550:94)
    at TextEditor.module.exports.TextEditor.getText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1031:32)
    at EditorEvents.buildEvent (/packages/kite/lib/editor-events.js:82:23)
    at EditorEvents.focus (/packages/kite/lib/editor-events.js:28:20)
    at HTMLElement.EditorEvents.subscriptions.add.DisposableEvent (/packages/kite/lib/editor-events.js:23:12)
    at HTMLElement.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:158:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:337:28)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:715:25)
```

### Commands

```
```

### Non-Core Packages

```
apm-publish 0.3.2 
atom-runner 2.7.1 
autocomplete-python 1.10.3 
build-npm-apm 0.12.0 
kite 0.52.0 
script 3.17.3 
```

**Comment by jansorg** [comment]
@rahulbhat44 Do you still experience this?
Sorry for this really late reply!

**Comment by jansorg** [comment]
Closing due to missing feedback
