### ISSUE TITLE
unable to activate

### ISSUE THREAD

**Issue by nakulstar95** [kiteco/atom-plugin#281]
Macbook Air
os High seira

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.55.0

### Stack Trace

Failed to activate the kite package

```
At Cannot read property 'priority' of undefined

TypeError: Cannot read property 'priority' of undefined
    at StatusBarView.module.exports.StatusBarView.addRightTile (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:76:113)
    at Object.consumeStatusBar (/packages/kite/lib/kite.js:438:15)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at Installer.onFinish (/packages/autocomplete-python/lib/main.coffee:209:25)
    at endProgress (/packages/autocomplete-python/node_modules/kite-installer/lib/installer.js:293:14)
    at prom.then (/packages/autocomplete-python/node_modules/kite-installer/lib/installer.js:303:9)
```

### Commands

```
  5x -7:53.4.0 core:confirm (input.hidden-input)
  4x -7:50.9.0 core:backspace (input.hidden-input)
  7x -7:46.5.0 core:confirm (input.hidden-input)
     -7:42.9.0 editor:consolidate-selections (input.hidden-input)
     -7:42.9.0 core:cancel (input.hidden-input)
     -7:42.4.0 editor:consolidate-selections (input.hidden-input)
     -7:42.4.0 core:cancel (input.hidden-input)
     -7:40.7.0 core:backspace (input.hidden-input)
     -7:40 editor:consolidate-selections (input.hidden-input)
     -7:40 core:cancel (input.hidden-input)
     -7:38 editor:delete-to-beginning-of-word (input.hidden-input)
     -7:37 editor:consolidate-selections (input.hidden-input)
     -7:37 core:cancel (input.hidden-input)
     -7:36.4.0 editor:consolidate-selections (input.hidden-input)
     -7:36.4.0 core:cancel (input.hidden-input)
     -6:10.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.10.3 
indent-detective 0.1.1 
ink 0.7.8 
julia-client 0.6.5 
kite 0.55.0 
language-julia 0.13.0 
latex-completions 0.3.3 
python-debugger 0.2.0 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by jansorg** [comment]
@nakulstar95 Does this still happen?
We're sorry for this really late reply.

**Comment by jansorg** [comment]
Closing due to missing feedback
