### ISSUE TITLE
Uncaught Error: Cannot find module './kite'

### ISSUE THREAD

**Issue by AhmedSaidAlamri** [kiteco/atom-plugin#292]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.58.0

### Stack Trace

Uncaught Error: Cannot find module './kite'

```
At module.js:472

Error: Cannot find module './kite'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at Object.getSuggestions (/packages/kite/lib/completions.js:32:25)
    at Object.getSuggestions (/packages/autocomplete-python/lib/main.coffee:273:37)
    at providers.forEach.provider (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1674:32)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1811:30)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1358:25)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3194:26)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:3165:42)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1357:23)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1323:23)
    at TextEditor.object.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1647:30)
```

### Commands

```
  2x -8:01.7.0 core:backspace (input.hidden-input)
     -8:00.8.0 core:confirm (input.hidden-input)
     -1:41 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:38.2.0 core:confirm (input.hidden-input)
     -1:31.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  8x -1:21.7.0 core:backspace (input.hidden-input)
     -1:07.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
 19x -0:54.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
kite 0.58.0 
my-package 0.0.0 
script 3.13.0 
```

**Comment by jansorg** [comment]
@AhmedSaidAlamri Sorry for this really late reply! Won't happen again...
Is the Kite plugin working after reinstalling it?

**Comment by jansorg** [comment]
Closing due to missing feedback
