### ISSUE TITLE
Uncaught TypeError: Kite.setStatusLabel is not a function

### ISSUE THREAD

**Issue by ggorkemk** [kiteco/atom-plugin#294]
Steps:

1. Open any python file
2. Try to write `print("hello world!")` 

After this it gives out this error.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.59.0

### Stack Trace

Uncaught TypeError: Kite.setStatusLabel is not a function

```
At C:\Users\ganig\.atom\packages\kite\lib\kite-editor.js:70

TypeError: Kite.setStatusLabel is not a function
    at subs.add.editor.onDidChangeCursorPosition (/packages/kite/lib/kite-editor.js:70:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:2687:31)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.23.3/resources/app/src/selection.js:914:25)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.23.3/resources/app/src/selection.js:21:45)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/marker.js:428:26)
    at Marker.module.exports.Marker.update (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/marker.js:369:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/marker-layer.js:290:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1631:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:998:20)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:944:20)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:2680:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:2491:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor-component.js:1810:25)
```

### Commands

```
     -0:27.6.0 core:close (div.tool-panel.tree-view)
  3x -0:18.7.0 core:backspace (input.hidden-input)
     -0:17 core:confirm (input.hidden-input)
     -0:11.5.0 editor:consolidate-selections (input.hidden-input)
     -0:11.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.9 
atom-clock 0.1.16 
autocomplete-python 1.10.5 
browser-plus 0.0.98 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.15 
git-plus 7.10.0 
highlight-selected 0.13.1 
Hydrogen 2.2.1 
intentions 1.1.5 
kite 0.59.0 
language-r 0.4.2 
language-scala 1.1.9 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
monokai 0.24.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
python-jedi 0.3.8 
split-diff 1.5.2 
todo 0.6.0 
```

**Comment by jansorg** [comment]
@abe33 Could you look into this, please?
