### ISSUE TITLE
Uncaught TypeError: Cannot read property '9' of undefined

### ISSUE THREAD

**Issue by mikkelyang** [kiteco/atom-plugin#324]
[Enter steps to reproduce:]

In Atom, upon opening a python file this error appears:

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.70.0

### Stack Trace

Uncaught TypeError: Cannot read property '9' of undefined

```
At C:\Users\Hp\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor-component.js:963

TypeError: Cannot read property '9' of undefined
    at TextEditorComponent.renderedScreenLineForRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:963:37)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2399:33)
    at HTMLElement.screenPositionForPixelPosition (/app.asar/src/text-editor-element.js:250:32)
    at screenPositionForMouseEvent (/packages/kite/lib/utils.js:220:21)
    at HoverGesture.wordRangeForMouseEvent (/packages/kite/lib/gestures/mouse-event.js:25:22)
    at HTMLElement.subscription.DisposableEvent (/packages/kite/lib/gestures/word-hover.js:27:30)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
autocomplete-python 1.10.5 
kite 0.70.0 
platformio-ide-terminal 2.8.0 
```

**Comment by jansorg** [comment]
@mikkelyang Thanks for the report!
I've tried to reproduce this with the configuration you posted (Win 10 64bit with the plugins listed). I'm not getting any exception here.
Does this happen repeatedly or just sometimes?
Do you see this for every  Python file or for just a few?

Thanks!

**Comment by abe33** [comment]
Sadly that's some random issue coming from Atom's API, I'll close the issue as we're no longer computing a range for hover so this error should no longer appear.
