### ISSUE TITLE
Uncaught Error: Cannot find module './elements/kite-hover'

### ISSUE THREAD

**Issue by n-pretorious** [kiteco/atom-plugin#373]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.77.0

### Stack Trace

Uncaught Error: Cannot find module './elements/kite-hover'

```
At module.js:472

Error: Cannot find module './elements/kite-hover'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/kite/lib/overlay-manager.js:5:19)
    at /packages/kite/lib/overlay-manager.js:120:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at subs.add.hoverGesture.onDidDeactivate (/packages/kite/lib/kite-editor.js:67:49)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at HoverGesture.deactivate (/packages/kite/lib/gestures/base.js:43:38)
    at HTMLElement.subscription.DisposableEvent (/packages/kite/lib/gestures/word-hover.js:36:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
kite 0.77.0 
python-indent 1.1.4 
python-snippets 1.9.0 
teletype 0.10.0 
```

**Comment by jansorg** [comment]
@n-pretorious Please reopen if this is still happening for you
