### ISSUE TITLE
Uncaught Error: Cannot find module './elements/kite-login'

### ISSUE THREAD

**Issue by fikrifikar** [kiteco/atom-plugin#410]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.90.0

### Stack Trace

Uncaught Error: Cannot find module './elements/kite-login'

```
At module.js:472

Error: Cannot find module './elements/kite-login'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.26.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.26.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.26.1/resources/app/src/native-compile-cache.js:66:33)
    at KiteApp.login (/packages/kite/lib/kite-app.js:336:35)
    at onDidClick (/packages/kite/lib/notifications-center.js:296:36)
    at NotificationElement.button.onDidClick (/packages/kite/lib/notifications-center.js:456:25)
    at HTMLAnchorElement.<anonymous> (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/notifications/lib/notification-element.js:147:48)
```

### Commands

```
  4x -1:02.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
autocomplete-python-jedi 1.10.3-0 
build 0.70.0 
build-python 0.9.3 
busy-signal 1.4.3 
ide-python 0.9.2 
kite 0.90.0 
python-debugger 0.2.0 
python-indent 1.1.5 
script 3.17.3 
```

**Comment by abe33** [comment]
Hello @fikrifikar, this kind of errors regularly surface when something went wrong during the install of the plugin or its dependencies. In that case it looks like the login screen UI was not properly installed along the plugin. Could you uninstall then reinstall the plugin, it should solve this kind of issues immediately.
