### ISSUE TITLE
Kite installation hangs

### ISSUE THREAD

**Issue by Lokdal** [kiteco/atom-plugin#470]
Leave an "undefined" error after logging in and downloading kite. Sent an email to feedback@kite.com.

**Comment by abe33** [comment]
Hello @Lokdal, thanks for the report, could you provide me with the logs in the developer tools? maybe there's more useful information here.

**Comment by Lokdal** [comment]
I have been in touch with Daniel over email, maybe he's started working on it already. Here's the javascript console output (is that what you mean?)

09:43:50.099 C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067 ::onDidChangeTitle does not return a valid Disposable! Install
c.(anonymous function) @ C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067
09:43:50.100 C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067 ::onDidChangeModified does not return a valid Disposable! Install
c.(anonymous function) @ C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067
09:43:50.166 C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067 error parsing gitconfig: Error: ENOENT: no such file or directory, open 'C:\Users\USER\.gitconfig'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:510:29)
    at Promise (C:\Users\USER\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\install\get-email.js:14:35)
    at new Promise (<anonymous>)
    at GetEmail.start (C:\Users\USER\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\install\get-email.js:13:12)
    at Flow.executeStep (C:\Users\USER\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\install\flow.js:38:6)
    at Flow.start (C:\Users\USER\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\install\flow.js:22:14)
    at Install.start (C:\Users\USER\.atom\packages\autocomplete-python\node_modules\kite-installer\lib\install.js:54:22)
    at KiteApp.showInstallFlow (C:\Users\USER\.atom\packages\kite\lib\kite-app.js:283:13)
    at KiteAPI.canInstallKite.then (C:\Users\USER\.atom\packages\kite\lib\kite-app.js:249:12)
    at <anonymous>
c.(anonymous function) @ C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067
09:43:50.431 ssl.google-analytics.com/collect?t=event&ec=window&ea=ended&ev=62179&v=1&aip=1&tid=UA-3769691-33&cid=ab979cb0-9314-41f9-a7bf-50724bc75879&an=atom&av=1.29.0&cd2=x64&cd3=x64&cm1=91&cm2=78&sr=1920x1080&vp=1028x988&aiid=stable Failed to load resource: net::ERR_CONNECTION_REFUSED
09:43:50.432 ssl.google-analytics.com/collect?t=event&ec=window&ea=started&v=1&aip=1&tid=UA-3769691-33&cid=ab979cb0-9314-41f9-a7bf-50724bc75879&an=atom&av=1.29.0&cd2=x64&cd3=x64&cm1=91&cm2=78&sr=1920x1080&vp=1028x988&aiid=stable Failed to load resource: net::ERR_CONNECTION_REFUSED
09:43:51.562 ssl.google-analytics.com/collect?t=timing&utc=shell&utv=load&utt=1380&v=1&aip=1&tid=UA-3769691-33&cid=ab979cb0-9314-41f9-a7bf-50724bc75879&an=atom&av=1.29.0&cd2=x64&cd3=x64&cm1=91&cm2=78&sr=1920x1080&vp=1028x988&aiid=stable Failed to load resource: net::ERR_CONNECTION_REFUSED
09:43:51.562 ssl.google-analytics.com/collect?t=timing&utc=core&utv=load&utt=312&v=1&aip=1&tid=UA-3769691-33&cid=ab979cb0-9314-41f9-a7bf-50724bc75879&an=atom&av=1.29.0&cd2=x64&cd3=x64&cm1=99&cm2=83&sr=1920x1080&vp=1028x988&aiid=stable Failed to load resource: net::ERR_CONNECTION_REFUSED
09:43:51.591 localhost:46624/clientapi/metrics/counters Failed to load resource: net::ERR_CONNECTION_REFUSED
09:43:51.635 localhost:46624/clientapi/metrics/counters Failed to load resource: net::ERR_CONNECTION_REFUSED
09:43:52.583 C:\Users\USER\.atom\packages\kite\node_modules\rollbar\dist\rollbar.js:5067 Unable to locate git workspace root for C:\Users\USER\OneDrive - University of Ottawa\School\Python Course\basics. Expected if C:\Users\USER\OneDrive - University of Ottawa\School\Python Course\basics is not in a git repository. GitError: git rev-parse --show-toplevel in C:\Users\USER\OneDrive - University of Ottawa\School\Python Course\basics exited with code 128
stdout: 
stderr: fatal: not a git repository (or any of the parent directories): .git

    at new GitError (C:\Users\USER\AppData\Local\atom\app-1.29.0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:121:24)
    at Promise (C:\Users\USER\AppData\Local\atom\app-1.29.0\resources\app\node_modules\github\lib\git-shell-out-strategy.js:385:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Vincent LeBlanc
 
Étudiant au doctorat en Psychologie Expérimentale / PhD Candidate in Experimental Psychology
 
https://www.researchgate.net/profile/Vincent_Leblanc2 [https://www.researchgate.net/profile/Vincent_Leblanc2]
 
Université d'Ottawa / University of Ottawa
Faculté des Sciences Sociales / Faculty of Social Sciences
École de Psychologie / School of Psychology
136 Jean Jacques Lussier
Pavillon Vanier / Vanier Hall
Ottawa, Ontario, Canada
K1N 6N5
On 08-08-2018 06:15:29, Cédric Néhémie <notifications@github.com> wrote:
Hello @Lokdal [https://github.com/Lokdal], thanks for the report, could you provide me with the logs in the developer tools? maybe there's more useful information here.

**Comment by its-dhung** [comment]
Will address this in the autocomplete-python repo
