### ISSUE TITLE
Uncaught TypeError: KiteAPI.emitWhitelistedPathDetected is not a function

### ISSUE THREAD

**Issue by alexapke** [kiteco/atom-plugin#563]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.138.0

### Stack Trace

Uncaught TypeError: KiteAPI.emitWhitelistedPathDetected is not a function

```
At /Users/alex/.atom/packages/kite/lib/editor-events.js:98

TypeError: KiteAPI.emitWhitelistedPathDetected is not a function
    at EditorEvents.mergeEvents (/packages/kite/lib/editor-events.js:98:19)
    at timeout.setTimeout (/packages/kite/lib/editor-events.js:62:42)
```

### Commands

```
     -6:39.9.0 editor:newline (input.hidden-input)
     -6:37 core:backspace (input.hidden-input)
     -6:36.6.0 editor:newline (input.hidden-input)
  2x -6:28 core:backspace (input.hidden-input)
     -5:52 core:move-right (input.hidden-input)
  4x -5:51.6.0 core:backspace (input.hidden-input)
     -5:37.8.0 core:move-right (input.hidden-input)
     -5:36.2.0 editor:newline (input.hidden-input)
     -5:35.7.0 snippets:next-tab-stop (input.hidden-input)
     -5:35.7.0 snippets:expand (input.hidden-input)
     -5:35.7.0 editor:indent (input.hidden-input)
 10x -4:34.9.0 core:move-left (input.hidden-input)
  2x -4:26.4.0 core:move-right (input.hidden-input)
     -4:25.6.0 editor:newline (input.hidden-input)
     -0:40.2.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:16.8.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
autocomplete-python 1.11.0 
kite 0.138.0 
python-indent 1.1.6 
script 3.18.1 
```

**Comment by its-dhung** [comment]
Hi @alexapke, this has been fixed - please update the Kite package to `0.139.0`. Apologies for the inconvenience!
