### ISSUE TITLE
Uncaught TypeError: KiteAPI.emitWhitelistedPathDetected is not a function

### ISSUE THREAD

**Issue by fatih-erarslan** [kiteco/atom-plugin#564]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.138.0

### Stack Trace

Uncaught TypeError: KiteAPI.emitWhitelistedPathDetected is not a function

```
At /Users/fatih/.atom/packages/kite/lib/editor-events.js:98

TypeError: KiteAPI.emitWhitelistedPathDetected is not a function
    at EditorEvents.mergeEvents (/packages/kite/lib/editor-events.js:98:19)
    at timeout.setTimeout (/packages/kite/lib/editor-events.js:62:42)
```

### Commands

```
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-python-virtualenv 1.0.2 
django-atom 0.2.4 
django-templates 0.5.0 
django-test-runner 0.5.0 
django-wrap-i18n 0.6.0 
framer-syntax 1.1.0 
framer-ui 2.0.0 
Hydrogen 2.7.0 
kite 0.138.0 
language-django 0.1.1 
language-mongodb 0.3.1 
project-environment 1.0.4 
teletype 0.13.3 
unleash-django 1.3.2 
```

**Comment by its-dhung** [comment]
Hi @fatih-erarslan, this has been fixed - please update the Kite package to `0.139.0`. Apologies for the inconvenience!
