### ISSUE TITLE
Unable to install 0.9.2 update

### ISSUE THREAD

**Issue by agraubert** [kiteco/atom-plugin#61]
Atom updating of kite from 0.8.8 to 0.9.2 fails with the following error:

```Updating to “kite@0.9.2” failed.Hide output…

> oniguruma@6.1.1 install /private/var/folders/np/wx7n9w3n7cxgctg0t5py6txc0000gp/T/apm-install-dir-117114-6544-160aeiy/node_modules/kite/node_modules/oniguruma
> node-gyp rebuild

/private/var/folders/np/wx7n9w3n7cxgctg0t5py6txc0000gp/T/apm-install-dir-117114-6544-160aeiy
`-- (empty)


(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/np/wx7n9w3n7cxgctg0t5py6txc0000gp/T/apm-install-dir-117114-6544-160aeiy/node_modules/kite/node_modules/oniguruma
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/np/wx7n9w3n7cxgctg0t5py6txc0000gp/T/apm-install-dir-117114-6544-160aeiy/package.json'
npm WARN apm-install-dir-117114-6544-160aeiy No description
npm WARN apm-install-dir-117114-6544-160aeiy No repository field.
npm WARN apm-install-dir-117114-6544-160aeiy No README data
npm WARN apm-install-dir-117114-6544-160aeiy No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/agrauber/.atom/.apm/.apmrc" "--userconfig" "/Users/agrauber/.atom/.apmrc" "install" "/private/var/folders/np/wx7n9w3n7cxgctg0t5py6txc0000gp/T/d-117114-6544-lu89z8/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/np/wx7n9w3n7cxgctg0t5py6txc0000gp/T/apm-install-dir-117114-6544-160aeiy/npm-debug.log
npm ERR! code 1

17,201
kite 0.8.8
Python programming copilot — Kite shows cloud-powered completions, documentation, and examples.
kiteco
UPDATE TO 0.9.2SETTINGSUNINSTALLDISABLE
```

It looks like this may derive from a python version error, but it's never caused any issues before

**Comment by abe33** [comment]
Hi @agraubert, I've fixed that in v0.9.3, I was relying on a github library for the syntax-highlighting (one based on Atom's grammar system), but didn't expect it'd break at install. Now it's only relying on Atom's code for that purpose.
