### ISSUE TITLE
Failed to activate the kite package

### ISSUE THREAD

**Issue by acebigdata** [kiteco/atom-plugin#62]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.9.5

### Stack Trace

Failed to activate the kite package

```
At Command failed: C:\Users\isaac.zhou\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat
'reg' is not recognized as an internal or external command,
operable program or batch file.


Error: Command failed: C:\Users\isaac.zhou\.atom\packages\kite\node_modules\kite-installer\lib\support\read-arch.bat
'reg' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:495:13)
    at Object.execSync (child_process.js:535:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:680:22)
    at Object.arch (/packages/kite/node_modules/kite-installer/lib/support/windows.js:64:33)
    at Object.isOSVersionSupported (/packages/kite/node_modules/kite-installer/lib/support/windows.js:73:17)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/support/windows.js:77:17)
    at Object.isKiteSupported (/packages/kite/node_modules/kite-installer/lib/state-controller.js:62:25)
    at Object.isKiteInstalled (/packages/kite/node_modules/kite-installer/lib/state-controller.js:72:17)
    at Object.isKiteRunning (/packages/kite/node_modules/kite-installer/lib/state-controller.js:128:17)
    at Object.isKiteReachable (/packages/kite/node_modules/kite-installer/lib/state-controller.js:153:17)
    at Object.isUserAuthenticated (/packages/kite/node_modules/kite-installer/lib/state-controller.js:175:17)
    at Object.isPathWhitelisted (/packages/kite/node_modules/kite-installer/lib/state-controller.js:273:17)
    at Object.handleState (/packages/kite/node_modules/kite-installer/lib/state-controller.js:36:17)
    at KiteApp.checkPath (/packages/kite/lib/kite-app.js:285:28)
    at KiteApp.connect (/packages/kite/lib/kite-app.js:138:17)
    at Object.connect (/packages/kite/lib/kite.js:208:18)
    at Object.activate (/packages/kite/lib/kite.js:188:17)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.8.54 
insert-timestamp 0.2.4 
kite 0.9.5 
language-scala 1.1.8 
platformio-ide-terminal 2.2.3 
```

**Comment by abe33** [comment]
Hi @acebigdata, can you tell us which Windows version you're using?

**Comment by genepool99** [comment]
Same problem. Windows 7 Pro SP1

steps to reproduce:
1. Launch Atom after updating Kite to v0.11.0


**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.11.0


### Stack Trace

Failed to activate the kite package

```
At UNKNOWN: unknown error, open 'C:\Users\avi\.atom\compile-cache\style-manager\8a89ab8dff4ff2185dffff0f8ec95949b01e9c4a'

Error: UNKNOWN: unknown error, open 'C:\Users\avi\.atom\compile-cache\style-manager\8a89ab8dff4ff2185dffff0f8ec95949b01e9c4a'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at StyleManager.addStyleSheet (/app.asar/src/style-manager.js:149:12)
    at Package.module.exports.Package.activateStylesheets (/app.asar/src/package.js:287:58)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:211:14)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
.bin undefined 
angularjs 0.4.0 
atom-typescript 10.1.14 
autocomplete-ionic-framework 0.2.2 
autocomplete-python 1.8.57 
color-picker 2.2.5 
ionic-preview 0.7.0 
kite 0.11.0 
linter 1.11.23 
webbox-color 0.5.9 
```

**Comment by smrati** [comment]
i am also facing same issue on mac version 10.10.5
`SyntaxError: Unexpected token *
    at Module._compile (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/smrati/.atom/packages/kite/lib/data-loader.js:20:25)
    at Module._compile (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/smrati/.atom/packages/kite/lib/completions.js:4:20)
    at Module._compile (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/smrati/.atom/packages/kite/lib/kite.js:10:21)
    at Module._compile (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:718:27)
    at Package.module.exports.Package.activateNow (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:460:29
    at exit (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Users/smrati/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)`

**Comment by conmarap** [comment]
[Enter steps to reproduce below:]

1. Install the package
2. Error pops up after the completion of the installation

**Atom Version**: 1.7.2
**System**: Ubuntu 16.04.2
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package, v0.19.0


### Stack Trace

Failed to activate the kite package

```
At Unexpected token {

SyntaxError: Unexpected token {
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpmd",
      "language-jsx",
      "language-jsx",
      "language-jsx",
      "language-actionscript",
      "nuclide-language-hack",
      "metrics",
      "autocomplete-erlang",
      "nuclide-flow",
      "linter-jslint",
      "nuclide-code-format",
      "nuclide-type-hint",
      "language-elixir",
      "language-flex",
      "linter-twig",
      "Stylus",
      "atom-jade",
      "atom-terminal",
      "autocomplete-glsl",
      "atom-autocomplete-php",
      "language-bison",
      "linter-gcc",
      "latex-autocomplete",
      "Tern",
      "love-launcher",
      "autocomplete-love",
      "autocomplete-php",
      "file-watcher",
      "flow-ide",
      "git-time-machine",
      "hyperclick",
      "hyperclick-love",
      "ink",
      "latex",
      "latex-plus",
      "latextools",
      "linter-emscripten",
      "linter-luaparse",
      "linter-oclitnt",
      "love-ide",
      "markdown-preview-plus",
      "markdown-pdf",
      "racer",
      "tool-bar",
      "atom-ternjs",
      "language-julia"
    ],
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.2.5
emmet, v2.4.3
firewatch-syntax, v1.0.1
kite, v0.19.0
linter, v1.11.18
linter-csslint, v1.3.4
linter-jshint, v3.0.3
linter-php, v1.3.1
linter-rust, v0.7.2
merge-conflicts, v1.4.4
minimap, v4.25.7
pdf-view, v0.55.0
pigments, v0.37.0

# Dev
No dev packages
```

**Comment by Westen0x** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.6
**System**: Kali GNU/Linux
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package, v0.20.2


### Stack Trace

Failed to activate the kite package

```
At Unexpected token *

SyntaxError: Unexpected token *
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/.../.../.atom/packages/kite/lib/data-loader.js:22:25)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/.../.../.atom/packages/kite/lib/completions.js:4:20)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/.../.../.atom/packages/kite/lib/kite.js:10:21)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
angularjs, v0.4.0 (inactive)
atom-beautify, v0.29.17 (inactive)
compare-files, v0.8.0 (inactive)
fold-functions, v0.5.0 (inactive)
javascript-snippets, v1.2.1 (inactive)
kite, v0.20.2 (inactive)
linter, v1.11.18 (inactive)
linter-jshint, v3.0.3 (inactive)
linter-python-pep8, v0.2.0 (inactive)
node-debugger, v1.10.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.3 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by lucasmocellin** [comment]
happened here as well:

Stack Trace

Failed to activate the kite package
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.27.0


### Stack Trace

Failed to activate the kite package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:1)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:1)
    at requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:110:1)
    at Object.requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:31:1)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:107:1)
    at Object.consumeProvider_2_0 (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:86:1)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:1)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:374:1
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:185:1)
    at Object.enablePackage (/packages/autocomplete-python/node_modules/kite-installer/lib/atom-helper.js:42:33)
    at /packages/autocomplete-python/lib/main.coffee:224:20
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:1)
    at SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:229:1)
    at HTMLInputElement.changeHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:174:1)
```

### Commands

```
     -3:08.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.8.64 
highlight-selected 0.13.1 
hyperclick 0.0.40 
kite 0.27.0 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
```

**Comment by overkillx** [comment]
Issue is still present in kite 0.49.0 (Atom 1.21.1 x64) on Windows 7 Professional SP1.<br>
I was however able to resolve this:
1. Fully exit Atom
2. Kill the Kite process
3. Start the Kite process
4. Start Atom

**Comment by jansorg** [comment]
@aislingdailey Thanks!
Restarting kite will trigger an update of Kite's Atom plugin.
If anyone  of you still experiences this issue with the current versions of Kite and the plugin please create a new issue.
