### ISSUE TITLE
Failed to activate the kite package

### ISSUE THREAD

**Issue by ryooriyagami** [kiteco/atom-plugin#663]
Failed to activate the kite package

Unexpected token >>>
Hide Stack Trace
C:\Users\SAM\.atom\packages\kite\dist\main.js:6165
>>>>>>> Patch autocomplete-plus/snippets insert(...) to not insert indentation for Kite completions.
^^^
SyntaxError: Unexpected token >>>
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:146322)
    at Module.get_Module._compile (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:147206)
    at Object.value [as .js] (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/SAM/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:1:721712)
    at Package.requireMainModule (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3338526)
    at Package.activateNow (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3326510)
    at measure (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3326288)
    at Package.measure (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3323898)
    at activationPromise.activationPromise.Promise (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3326148)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3326091)
    at PackageManager.activatePackage (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:382452)
    at C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:942215
    at r (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:936821)
    at n (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14:1125047)
    at ChildProcess.o.process.on.e (C:\Users\SAM\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14:1125253)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child

**Comment by tonycheang** [comment]
Thanks for reporting! We just re-released; let us know if you're still encountering this error.

**Comment by AKh-47** [comment]
> Thanks for reporting! We just re-released; let us know if you're still encountering this error.

Still Having this issue

**Comment by metalogical** [comment]
@AKh-47 what version of the Kite plugin for Atom are you running? It should be 0.182.0

**Comment by AKh-47** [comment]
> @AKh-47 what version of the Kite plugin for Atom are you running? It should be 0.182.0

Just got the update. Thanks!

**Comment by ATX1321** [comment]
It still doesn't work for me.

Failed to activate the kite package
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1219453)
    at CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1220421)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:162456)
    at Object.consumeProvider_2 (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:162154)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1119354)
    at ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3180262)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3188548)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3185524)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3184848)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3182458)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3184708)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3184651)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382700)
    at n.forEach.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377866)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377850)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334901)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1217348)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:337389)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334629)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:330423)
    at Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332446)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3182243)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:375564)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2636518)

**Comment by thiagodma** [comment]
Any solutions? The problem still exists...

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/lib/atom/node_modules/event-kit/dist/composite-disposable.js:162:11)
    at CompositeDisposable.add (/usr/lib/atom/node_modules/event-kit/dist/composite-disposable.js:106:13)
    at Object.consumeProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:84:21)
    at Object.consumeProvider_2 (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:57:17)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.activateServices (/usr/lib/atom/src/package.js:430:40)
    at Package.activateNow (/usr/lib/atom/src/package.js:246:14)
    at /usr/lib/atom/src/package.js:210:27
    at Package.measure (/usr/lib/atom/src/package.js:81:19)
    at /usr/lib/atom/src/package.js:204:14
    at new Promise (<anonymous>)
    at Package.activate (/usr/lib/atom/src/package.js:202:32)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:790:36)
    at /usr/lib/atom/src/package-manager.js:487:47
    at Array.forEach (<anonymous>)
    at /usr/lib/atom/src/package-manager.js:487:26
    at /usr/lib/atom/src/config.js:1145:16
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Config.emitChangeEvent (/usr/lib/atom/src/config.js:1343:27)
    at Config.setRawValue (/usr/lib/atom/src/config.js:1130:17)
    at Config.set (/usr/lib/atom/src/config.js:764:12)
    at Config.removeAtKeyPath (/usr/lib/atom/src/config.js:966:10)
    at Package.enable (/usr/lib/atom/src/package.js:68:24)
    at PackageManager.enablePackage (/usr/lib/atom/src/package-manager.js:278:12)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:364:25)

**Comment by metalogical** [comment]
Please check and report the version of the plugin that you are running

**Comment by thiagodma** [comment]
Actually I've just solved the problem. Just run:

`bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"`

At least it worked for me

**Comment by osamaa96** [comment]
please i have this problem and i dont know how to fix it 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.185.0


### Stack Trace

Failed to activate the kite package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1193748)
    at CompositeDisposable.add (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1194716)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:162524)
    at Object.consumeProvider_2 (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:162222)
    at Provider.provide (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:1086113)
    at ServiceHub.provide (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3282710)
    at Package.activateServices (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3290996)
    at Package.activateNow (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3287972)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3287296
    at Package.measure (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3284906)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3287156
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3287099)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:382942)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:378108
    at Array.forEach (<anonymous>)
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:378092
    at ~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:335143
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1190202)
    at Emitter.emit (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:1191643)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:337631)
    at Config.setRawValue (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:334871)
    at Config.set (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:330665)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:332688)
    at Package.enable (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:3284691)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:11:375806)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:2571668)
```

### Commands

```
     -6:52.5.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:49.2.0 welcome:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:26.3.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
autocomplete-python 1.16.0 
ide-python 1.5.0 
kite 0.185.0 
script 3.26.0 
```
