### ISSUE TITLE
kite install error 

### ISSUE THREAD

**Issue by arydevy** [kiteco/atom-plugin#684]
i try to install kite on linux atom and i get this eror
kited_error: Unable to download Kite. Unexpected exit code 12. cmd: /tmp/kite-installer.sh --download
and
Error: kited_error: Unable to download Kite. Unexpected exit code 12.
cmd: /tmp/kite-installer.sh --download
    at ChildProcess. (/home/arydev/.atom/packages/autocomplete-python/node_modules/kite-connector/lib/support/linux.js:165:20)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Socket. (internal/child_process.js:403:11)
    at Socket.emit (events.js:194:13)
    at Pipe. (net.js:593:12)

![image](https://user-images.githubusercontent.com/62546648/88267985-576e3a80-ccda-11ea-972e-8c5141bad136.png)

**Comment by its-dhung** [comment]
Please try downloading and installing Kite from https://kite.com/download.
